# Location of top-level MicroPython directory
MPY_DIR = ~/Tools/micropython

# Name of module
MOD = bufxor

# Source files (.c or .py)
SRC = bufxor.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
# ARCH = xtensawin
ARCH = xtensa

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
