import CrabUI as ui
import oled

manager = ui.Manager(oled)
root = ui.ListMenu()

giveme = ui.TextDialog('点赞投币收藏')
a = ui.Item(root, 'CrabUI')
ui.NumberSelector(a, 10, -20, 50, 5, True, link=lambda n: print(n))
ui.Item(root, f'version{ui.__version__}')
ui.Item(root, '给个三连吧', link=giveme.pop)
ui.Item(root, '测试') 
ui.Item(root, 'OledTest')
ui.Item(root, 'Hello! Welcome to CrabUI! It\'s a smooth ui write in micropython.Have a good time with it!')
ui.Item(root, '你好!欢迎来到CrabUI!它是一个丝滑的ui框架，使用micropython编写')
ui.Item(root, '我的ui框架')
ui.Item(root, 'Micropython')
ui.Item(root, 'Page2', link=lambda: manager.set_menu(page2))
ui.Item(root, '这是测试')
ui.Item(root, '新的消息')
ui.Item(root, '用户图形界面')
ui.Item(root, 'ABCDEFG')
ui.Item(root, 'HIJKLMN')
ui.Item(root, 'OPQRSTU')
ui.Item(root, 'VWXYZ()')
ui.Item(root, 'Copyright 版权声明 (c) 2025 kaixin168sxz(kaixin1106)')
ui.Item(root, '流畅程度测试')

page2 = ui.IconMenu()
ui.Item(page2, 'files/a.pbm')
ui.Item(page2, 'files/b.pbm', link=lambda: manager.set_menu(page3))

page3 = ui.IconMenu()
ui.Item(page3, 'files/b.pbm', '1111111')
ui.Item(page3, 'files/b.pbm', '2222222')
ui.Item(page3, 'files/b.pbm', '1212121212121212121')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')
ui.Item(page3, 'files/b.pbm')

manager.set_menu(root)

while True:
    manager.update()